name: dart_frog_cors
description: CORS middleware for dart_frog.
version: 2.0.0
repository: https://github.com/andyhorn/dart_frog_cors

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.16.0
dependencies:
  dart_frog: ^1.0.1
